name: models
description:  The Models package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  pro_lints: ^2.0.2
  test: ^1.25.3

