name: prisma_repositories
description: Prisma projects base data source
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  models:
    path: ../models
  orm: ^4.1.0
  prisma_orm:
    path: ../prisma_orm
  projects_repository:
    path: ../projects_repository
  users_repository:
    path: ../users_repository

dev_dependencies:
  mocktail: ^1.0.3

  pro_lints: ^2.0.2
  test: ^1.25.4

