name: auth
description:  The Auth data source package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  dart_jsonwebtoken: ^2.14.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  users_repository:
    path: ../users_repository

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  pro_lints: ^2.0.2
  test: ^1.25.4

