name: auth_data_source
description:  The Auth data source package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  dart_jsonwebtoken: ^2.13.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  users_data_source:
    path: ../users_data_source

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  pro_lints: ^2.0.2
  test: ^1.25.4

