name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  auth_data_source:
    path: ./packages/auth_data_source
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.1.0
  dart_frog_request_logger: ^0.0.2
  models:
    path: ./packages/models
  prisma_data_source:
    path: ./packages/prisma_data_source
  projects_data_source:
    path: ./packages/projects_data_source
  users_data_source:
    path: ./packages/users_data_source

dev_dependencies:
  mocktail: ^1.0.3
  pro_lints: ^2.0.2
  test: ^1.25.3

