name: prisma_orm
description: Prisma orm
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  orm: ^4.1.0

dev_dependencies:
  mocktail: ^1.0.3
  pro_lints: ^2.0.2
  test: ^1.25.4

