name: prisma_projects_data_source
description: Prisma projects base data source
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  prisma_orm:
    path: ../prisma_orm
  projects_data_source:
    path: ../projects_data_source


dev_dependencies:
  mocktail: ^1.0.3

  pro_lints: ^2.0.2
  test: ^1.25.4

