name: lake_cli
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  analyzer: ^6.4.1
  args: ^2.5.0
  cli_completion: ^0.5.0
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  mason_logger: ^0.2.15
  path: ^1.9.0
  pub_updater: ^0.4.0
  pubspec_parse: ^1.2.3
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  build_version: ^2.1.1
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  pro_lints: ^2.0.2
  test: ^1.25.4

executables:
  lake:
