name: api_client_builder_annotations
description:  The ApiClientBuilderAnnotations package.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  meta: ^1.14.0

dev_dependencies:
  mocktail: ^1.0.3
  pro_lints: ^2.0.2
  test: ^1.25.3

